module_dict={
    "headers":{'Content-Type': 'application/json; charset=utf-8'},
    "timeout":20,
}

registry_api_dict={
    "AKASH" : "https://validators.cosmos.directory/chains/akash",
    "ASSETMANTLE" : "https://validators.cosmos.directory/chains/assetmantle",
    "AXELAR" : "https://validators.cosmos.directory/chains/axelar",
    "BAND" : "https://validators.cosmos.directory/chains/bandchain",
    "BINANCE" : "",
    "BITCANNA" : "https://validators.cosmos.directory/chains/bitcanna",
    "BITSONG" : "https://validators.cosmos.directory/chains/bitsong",
    "CERBERUS" : "https://validators.cosmos.directory/chains/cerberus",
    "CERTIK" : "",
    "CHIHUAHUA" : "https://validators.cosmos.directory/chains/chihuahua",
    "COMDEX" : "https://validators.cosmos.directory/chains/comdex",
    "COSMOS HUB" : "https://validators.cosmos.directory/chains/cosmoshub",
    "CRESCENT" : "https://validators.cosmos.directory/chains/crescent",
    "CRYPTO.ORG" : "https://validators.cosmos.directory/chains/cryptoorgchain",
    "CUDOS" : "https://validators.cosmos.directory/chains/cudos",
    "DESMOS" : "https://validators.cosmos.directory/chains/desmos",
    "EMONEY" : "https://validators.cosmos.directory/chains/emoney",
    "EVMOS" : "https://validators.cosmos.directory/chains/evmos",
    "FETCH.AI" : "https://validators.cosmos.directory/chains/fetchhub",
    "GRAVITY BRIDGE" : "https://validators.cosmos.directory/chains/gravitybridge",
    "INJECTIVE" : "https://validators.cosmos.directory/chains/injective",
    "IRIS" : "https://validators.cosmos.directory/chains/irisnet",
    "JUNO" : "https://validators.cosmos.directory/chains/juno",
    "KAVA" : "https://validators.cosmos.directory/chains/kava",
    "KI CHAIN" : "https://validators.cosmos.directory/chains/kichain",
    "KONSTELLATION" : "https://validators.cosmos.directory/chains/konstellation",
    "LUM" : "https://validators.cosmos.directory/chains/lumnetwork",
    "MEDIBLOC" : "https://validators.cosmos.directory/chains/panacea",
    "NYX" : "",
    "OMNIFLIX" : "https://validators.cosmos.directory/chains/omniflixhub",
    "OSMOSIS" : "https://validators.cosmos.directory/chains/osmosis",
    "PERSISTENCE" : "https://validators.cosmos.directory/chains/persistence",
    "PROVENANCE" : "https://validators.cosmos.directory/chains/provenance",
    "REGEN" : "https://validators.cosmos.directory/chains/regen",
    "RIZON" : "https://validators.cosmos.directory/chains/rizon",
    "SECRET" : "https://validators.cosmos.directory/chains/secretnetwork",
    "SENTINEL" : "https://validators.cosmos.directory/chains/sentinel",
    "SIFCHAIN" : "https://validators.cosmos.directory/chains/sifchain",
    "STARGAZE" : "https://validators.cosmos.directory/chains/stargaze",
    "STARNAME" : "https://validators.cosmos.directory/chains/starname",
    "TGRADE" : "https://validators.cosmos.directory/chains/tgrade",
    "UMEE" : "https://validators.cosmos.directory/chains/umee",
}

api_dict={
"AKASH" : "https://akash-api.polkachu.com",
"ASSETMANTLE" : "https://assetmantle-api.polkachu.com",
"AXELAR" : "https://axelar-api.polkachu.com",
"BAND" : "https://rest.cosmos.directory/bandchain",
"BINANCE" : "",
"BITCANNA" : "https://bitcanna-api.polkachu.com",
"BITSONG" : "https://rest.cosmos.directory/bitsong",
"CERBERUS" : "https://cerberus-api.polkachu.com",
"CERTIK" : "https://certik-api.polkachu.com",
"CHIHUAHUA" : "https://chihuahua-api.polkachu.com",
"COMDEX" : "https://comdex-api.polkachu.com",
"COSMOS HUB" : "https://cosmos-api.polkachu.com",
"CRESCENT" : "https://mainnet.crescent.network:1317",
"CRYPTO.ORG" : "https://mainnet.crypto.org:1317",
"CUDOS" : "https://rest.cosmos.directory/cudos",
"DESMOS" : "https://rest.cosmos.directory/desmos",
"EMONEY" : "https://emoney.validator.network/api",
"EVMOS" : "https://evmos-api.theamsolutions.info",
"FETCH.AI" : "https://fetch-api.polkachu.com",
"GRAVITY BRIDGE" : "https://gravitychain.io:1317",
"INJECTIVE" : "https://lcd.injective.network",
"IRIS" : "https://lcd-iris.keplr.app",
"JUNO" : "https://juno-api.polkachu.com",
"KAVA" : "https://api.kava.io",
"KI CHAIN" : "https://kichain-api.polkachu.com",
"KONSTELLATION" : "https://konstellation-api.polkachu.com",
"LUM" : "https://rest.cosmos.directory/lumnetwork",
"MEDIBLOC" : "https://api.gopanacea.org/",
"NYX" : "https://nym-api.polkachu.com",
"OMNIFLIX" : "https://omniflixhub-api.skynetvalidators.com",
"OSMOSIS" : "https://osmosis.stakesystems.io",
"PERSISTENCE" : "https://rest.cosmos.directory/persistence",
"PROVENANCE" : "https://api.provenance.io",
"REGEN" : "https://rest.cosmos.directory/regen",
"RIZON" : "http://seed-1.mainnet.rizon.world:1317",
"SECRET" : "https://secret-4.api.trivium.network:1317",
"SENTINEL" : "https://lcd-sentinel.whispernode.com",
"SIFCHAIN" : "https://sifchain-api.polkachu.com",
"STARGAZE" : "https://stargaze-api.polkachu.com",
"STARNAME" : "https://rest.cosmos.directory/starname",
"TGRADE" : "https://api.mainnet-1.tgrade.confio.run",
"UMEE" : "https://api.aphrodite.main.network.umee.cc",
}

rpc_dict = {
"AKASH" : "https://akash-rpc.polkachu.com",
"ASSETMANTLE" : "https://assetmantle-rpc.polkachu.com",
"AXELAR" : "https://axelar.rpc.stake2.me",
"BAND" : "http://rpc.laozi1.bandchain.org",
"BINANCE" : "https://dataseed3.defibit.io",
"BITCANNA" : "https://bitcanna-rpc.polkachu.com",
"BITSONG" : "https://rpc-bitsong.itastakers.com",
"CERBERUS" : "https://cerberus-rpc.polkachu.com",
"CERTIK" : "https://certik-rpc.polkachu.com",
"CHIHUAHUA" : "https://chihuahua-rpc.polkachu.com",
"COMDEX" : "https://comdex-rpc.polkachu.com",
"COSMOS HUB" : "https://cosmos-rpc.polkachu.com",
"CRESCENT" : "https://mainnet.crescent.network:26657",
"CRYPTO.ORG" : "https://rpc-cryptoorgchain.ecostake.com",
"CUDOS" : "https://rpc.cosmos.directory/cudos",
"DESMOS" : "https://rpc.morpheus.desmos.network",
"EMONEY" : "https://rpc.cosmos.directory/emoney",
"EVMOS" : "https://evmos-rpc.theamsolutions.info",
"FETCH.AI" : "https://fetch-rpc.polkachu.com",
"GRAVITY BRIDGE" : "https://gravitychain.io:26657",
"INJECTIVE" : "https://injective-rpc.polkachu.com",
"IRIS" : "https://rpc-iris.keplr.app",
"JUNO" : "https://juno-rpc.polkachu.com",
"KAVA" : "https://rpc.kava.io",
"KI CHAIN" : "https://kichain-rpc.polkachu.com",
"KONSTELLATION" : "https://konstellation-rpc.polkachu.com",
"LUM" : "https://rpc.cosmos.directory/lumnetwork",
"MEDIBLOC" : "https://rpc.gopanacea.org",
"NYX" : "https://nym-rpc.polkachu.com",
"OMNIFLIX" : "https://omniflixhub-rpc.skynetvalidators.com",
"OSMOSIS" : "https://rpc.osmosis.zone",
"PERSISTENCE" : "https://rpc.core.persistence.one",
"PROVENANCE" : "https://rpc.provenance.io",
"REGEN" : "https://rpc.cosmos.directory/regen",
"RIZON" : "http://seed-1.mainnet.rizon.world:26657",
"SECRET" : "https://secret-4.api.trivium.network:26657",
"SENTINEL" : "https://rpc-sentinel.whispernode.com/",
"SIFCHAIN" : "https://sifchain-rpc.polkachu.com",
"STARGAZE" : "https://stargaze.rpc.stake2.me",
"STARNAME" : "https://rpc.cosmos.directory/starname",
"TGRADE" : "https://rpc.mainnet-1.tgrade.confio.run",
"UMEE" : "https://rpc.aphrodite.main.network.umee.cc",

}
